version: "3.8"
services:
    pokespa:
        build: .
        command: npm start
        environment:
            - CHOKIDAR_USEPOLLING="true"
        ports:
            - "3000:3000"
        volumes:
            - ./public:/app/public
            - ./src:/app/src
            - ./.gitignore:/app/.gitignore
            - ./Dockerfile:/app/Dockerfile
            - ./package-lock.json:/app/package-lock.json
            - ./package.json:/app/package.json
            - ./tsconfig.json:/app/tsconfig.json
            - ./README.md:/app/README.md
            - ./Docker-compose.dev.yaml:/app/Docker-compose.dev.yaml
            - ./.git:/app/.git
