version: "3.8"
services:
    pokespa:
        build: .
        command: npm start
        environment:
            - CHOKIDAR_USEPOLLING="true"
        ports:
            - "3000:3000"
        volumes:
            - .:/app